# Generated by Django 4.1.5 on 2023-02-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=50)),
                ('service_des', models.CharField(max_length=230)),
                ('service_icon', models.CharField(max_length=230)),
            ],
        ),
    ]
